export { createApiClient, type ApiClient } from "@/shared/api/client";
export { api } from "@/shared/api/runtime";

export type {
  ModelInfo,
  ModelsResponse,
  SpeechModelCapabilities,
} from "@/shared/api/models";

export type {
  ASRStatusResponse,
  ASRStreamCallbacks,
  ASRTranscribeRequest,
  ASRTranscribeResponse,
  DiarizationRecord,
  DiarizationRecordCreateRequest,
  DiarizationRecordRerunRequest,
  DiarizationRecordSummary,
  DiarizationRecordUpdateRequest,
  DiarizationRequest,
  DiarizationResponse,
  DiarizationSegment,
  DiarizationUtterance,
  DiarizationWord,
  STTRequest,
  STTResponse,
  SavedVoice,
  SavedVoiceCreateRequest,
  SavedVoiceSourceRouteKind,
  SavedVoiceSummary,
  SpeechHistoryRecord,
  SpeechHistoryRecordCreateRequest,
  SpeechHistoryRecordStreamCallbacks,
  SpeechHistoryRecordSummary,
  SpeechHistoryRoute,
  TTSGenerateResult,
  TTSGenerationStats,
  TTSRequest,
  TTSStreamCallbacks,
  TtsProjectCreateRequest,
  TtsProjectRecord,
  TtsProjectSegmentRecord,
  TtsProjectSegmentSplitRequest,
  TtsProjectSegmentUpdateRequest,
  TtsProjectSummary,
  TtsProjectUpdateRequest,
  TtsProjectVoiceMode,
  TranscriptionRecord,
  TranscriptionRecordCreateRequest,
  TranscriptionSegment,
  TranscriptionRecordStreamCallbacks,
  TranscriptionRecordSummary,
  TranscriptionWord,
} from "@/shared/api/audio";

export type {
  AgentEvent,
  AgentPlanningMode,
  AgentSession,
  AgentSessionCreateRequest,
  AgentToolCallRecord,
  AgentTurnRequest,
  AgentTurnResponse,
  ChatCompletionRequest,
  ChatCompletionResponse,
  ChatMessage,
  ChatStreamCallbacks,
  ChatStreamEvent,
  ChatThread,
  ChatThreadContentPart,
  ChatThreadCreateRequest,
  ChatThreadDetail,
  ChatThreadMessageRecord,
  ChatThreadSendMessageRequest,
  ChatThreadSendMessageResponse,
  ChatThreadStreamCallbacks,
  ChatThreadUpdateRequest,
  ResponsesCreateRequest,
  ResponsesObject,
  ResponsesStreamCallbacks,
} from "@/shared/api/chat";

export type {
  VoiceObservation,
  VoiceProfile,
  VoiceProfileUpdateRequest,
} from "@/shared/api/voice";
