export { createApiClient, type ApiClient } from "@/shared/api/client";
export { api } from "@/shared/api/runtime";

export type { ModelInfo, ModelsResponse } from "@/shared/api/models";

export type {
  ASRStatusResponse,
  ASRStreamCallbacks,
  ASRTranscribeRequest,
  ASRTranscribeResponse,
  DiarizationRecord,
  DiarizationRecordCreateRequest,
  DiarizationRecordSummary,
  DiarizationRequest,
  DiarizationResponse,
  DiarizationSegment,
  DiarizationUtterance,
  DiarizationWord,
  STTRequest,
  STTResponse,
  SavedVoice,
  SavedVoiceCreateRequest,
  SavedVoiceSourceRouteKind,
  SavedVoiceSummary,
  SpeechHistoryRecord,
  SpeechHistoryRecordCreateRequest,
  SpeechHistoryRecordStreamCallbacks,
  SpeechHistoryRecordSummary,
  SpeechHistoryRoute,
  SpeechToSpeechRequest,
  SpeechToSpeechResponse,
  SpeechToSpeechStreamCallbacks,
  TTSGenerateResult,
  TTSGenerationStats,
  TTSRequest,
  TTSStreamCallbacks,
  TranscriptionRecord,
  TranscriptionRecordCreateRequest,
  TranscriptionRecordStreamCallbacks,
  TranscriptionRecordSummary,
} from "@/shared/api/audio";

export type {
  AgentEvent,
  AgentPlanningMode,
  AgentSession,
  AgentSessionCreateRequest,
  AgentToolCallRecord,
  AgentTurnRequest,
  AgentTurnResponse,
  ChatCompletionRequest,
  ChatCompletionResponse,
  ChatMessage,
  ChatStreamCallbacks,
  ChatStreamEvent,
  ChatThread,
  ChatThreadContentPart,
  ChatThreadCreateRequest,
  ChatThreadDetail,
  ChatThreadMessageRecord,
  ChatThreadSendMessageRequest,
  ChatThreadSendMessageResponse,
  ChatThreadStreamCallbacks,
  ChatThreadUpdateRequest,
  ResponsesCreateRequest,
  ResponsesObject,
  ResponsesStreamCallbacks,
} from "@/shared/api/chat";
