export { createApiClient, type ApiClient } from "@/shared/api/client";
export { api } from "@/shared/api/runtime";
export type {
  CursorPageResult,
  CursorPaginationMeta,
  CursorPaginationQuery,
} from "@/shared/api/pagination";

export type {
  ModelInfo,
  ModelsResponse,
  SpeechModelCapabilities,
} from "@/shared/api/models";

export type {
  ASRStatusResponse,
  ASRStreamCallbacks,
  ASRTranscribeRequest,
  ASRTranscribeResponse,
  DiarizationRecord,
  DiarizationRecordCreateRequest,
  DiarizationProcessingStatus,
  DiarizationRecordRerunRequest,
  DiarizationRecordSummary,
  DiarizationSummaryStatus,
  DiarizationRecordUpdateRequest,
  DiarizationRequest,
  DiarizationResponse,
  DiarizationSegment,
  DiarizationUtterance,
  DiarizationWord,
  STTRequest,
  STTResponse,
  SavedVoice,
  SavedVoiceCreateRequest,
  SavedVoiceSourceRouteKind,
  SavedVoiceSummary,
  SpeechTextDiarizationJob,
  SpeechTextDiarizationJobCreateRequest,
  SpeechTextDiarizationSummary,
  SpeechHistoryProcessingStatus,
  SpeechHistoryRecord,
  SpeechHistoryRecordCreateRequest,
  SpeechHistoryRecordStreamCallbacks,
  SpeechHistoryRecordSummary,
  SpeechHistoryRoute,
  SpeechTextJob,
  SpeechTextJobCreateRequest,
  SpeechTextJobKind,
  SpeechTextJobPageQuery,
  SpeechTextJobProcessingStatus,
  SpeechTextJobQueryKind,
  SpeechTextJobSummary,
  SpeechTextJobSummaryStatus,
  SpeechTextTranscriptionJob,
  SpeechTextTranscriptionJobCreateRequest,
  SpeechTextTranscriptionSummary,
  TTSGenerateResult,
  TTSGenerationStats,
  TTSRequest,
  TTSStreamCallbacks,
  StudioProjectCreateRequest,
  StudioProjectExportFormat,
  StudioProjectFolderCreateRequest,
  StudioProjectFolderRecord,
  StudioProjectMetaRecord,
  StudioProjectMetaUpdateRequest,
  StudioProjectPronunciationCreateRequest,
  StudioProjectPronunciationRecord,
  StudioProjectRecord,
  StudioProjectRenderJobCreateRequest,
  StudioProjectRenderJobRecord,
  StudioProjectRenderJobStatus,
  StudioProjectRenderJobUpdateRequest,
  StudioProjectSegmentRecord,
  StudioProjectSegmentBulkDeleteRequest,
  StudioProjectSegmentCreateRequest,
  StudioProjectSegmentReorderRequest,
  StudioProjectSegmentSplitRequest,
  StudioProjectSegmentUpdateRequest,
  StudioProjectSnapshotCreateRequest,
  StudioProjectSnapshotRecord,
  StudioProjectSummary,
  StudioProjectUpdateRequest,
  StudioProjectVoiceMode,
  TranscriptionRecord,
  TranscriptionRecordCreateRequest,
  TranscriptionProcessingStatus,
  TranscriptionSummaryStatus,
  TranscriptionSegment,
  TranscriptionRecordStreamCallbacks,
  TranscriptionRecordSummary,
  TranscriptionWord,
} from "@/shared/api/audio";

export type {
  AgentEvent,
  AgentPlanningMode,
  AgentSession,
  AgentSessionCreateRequest,
  AgentToolCallRecord,
  AgentTurnRequest,
  AgentTurnResponse,
  ChatCompletionRequest,
  ChatCompletionResponse,
  ChatMessage,
  ChatStreamCallbacks,
  ChatStreamEvent,
  ChatThread,
  ChatThreadContentPart,
  ChatThreadCreateRequest,
  ChatThreadDetail,
  ChatThreadMessageRecord,
  ChatThreadSendMessageRequest,
  ChatThreadSendMessageResponse,
  ChatThreadStreamCallbacks,
  ChatThreadUpdateRequest,
  ResponsesCreateRequest,
  ResponsesObject,
  ResponsesStreamCallbacks,
} from "@/shared/api/chat";

export type {
  VoiceObservation,
  VoiceProfile,
  VoiceProfileUpdateRequest,
} from "@/shared/api/voice";

export type { OnboardingStateResponse } from "@/shared/api/onboarding";
export type {
  UpdateAnalyticsPreferenceRequest,
  UserPreferencesResponse,
} from "@/shared/api/preferences";
