export const PROVIDER_ORDER = [
  "Qwen",
  "OpenAI",
  "Liquid AI",
  "Google",
  "NVIDIA",
  "Mistral AI",
  "hexgrad",
  "Other",
] as const;

export interface ModelDetail {
  shortName: string;
  fullName: string;
  description: string;
  category: "tts" | "asr" | "chat";
  capabilities: string[];
  size: string;
}

export const MODEL_DETAILS: Record<string, ModelDetail> = {
  // TTS 0.6B Base models
  "Qwen3-TTS-12Hz-0.6B-Base": {
    shortName: "0.6B Base",
    fullName: "Qwen3-TTS 12Hz 0.6B Base",
    description: "Voice cloning with reference audio samples",
    category: "tts",
    capabilities: ["Voice Cloning"],
    size: "2.3 GB",
  },
  "Qwen3-TTS-12Hz-0.6B-Base-4bit": {
    shortName: "0.6B Base 4-bit",
    fullName: "Qwen3-TTS 12Hz 0.6B Base (MLX 4-bit)",
    description:
      "Quantized base model for lower VRAM without losing cloning support",
    category: "tts",
    capabilities: ["Voice Cloning", "4-bit"],
    size: "1.6 GB",
  },
  "Qwen3-TTS-12Hz-0.6B-Base-8bit": {
    shortName: "0.6B Base 8-bit",
    fullName: "Qwen3-TTS 12Hz 0.6B Base (MLX 8-bit)",
    description:
      "8-bit MLX weights for better quality while staying memory friendly",
    category: "tts",
    capabilities: ["Voice Cloning", "8-bit"],
    size: "1.9 GB",
  },
  "Qwen3-TTS-12Hz-0.6B-Base-bf16": {
    shortName: "0.6B Base BF16",
    fullName: "Qwen3-TTS 12Hz 0.6B Base (MLX bf16)",
    description: "BF16 MLX weights for highest fidelity base voices",
    category: "tts",
    capabilities: ["Voice Cloning", "BF16"],
    size: "2.3 GB",
  },
  // TTS 0.6B CustomVoice models
  "Qwen3-TTS-12Hz-0.6B-CustomVoice": {
    shortName: "0.6B CustomVoice",
    fullName: "Qwen3-TTS 12Hz 0.6B CustomVoice",
    description: "Pre-trained with 9 built-in voice profiles",
    category: "tts",
    capabilities: ["Text to Speech"],
    size: "2.3 GB",
  },
  "Qwen3-TTS-12Hz-0.6B-CustomVoice-4bit": {
    shortName: "0.6B Custom 4-bit",
    fullName: "Qwen3-TTS 12Hz 0.6B CustomVoice (MLX 4-bit)",
    description: "Quantized CustomVoice for laptops with tight memory",
    category: "tts",
    capabilities: ["Text to Speech", "4-bit"],
    size: "1.6 GB",
  },
  "Qwen3-TTS-12Hz-0.6B-CustomVoice-8bit": {
    shortName: "0.6B Custom 8-bit",
    fullName: "Qwen3-TTS 12Hz 0.6B CustomVoice (MLX 8-bit)",
    description:
      "Balanced 8-bit CustomVoice for better quality with reduced VRAM",
    category: "tts",
    capabilities: ["Text to Speech", "8-bit"],
    size: "1.8 GB",
  },
  "Qwen3-TTS-12Hz-0.6B-CustomVoice-bf16": {
    shortName: "0.6B Custom BF16",
    fullName: "Qwen3-TTS 12Hz 0.6B CustomVoice (MLX bf16)",
    description: "BF16 precision for premium CustomVoice rendering",
    category: "tts",
    capabilities: ["Text to Speech", "BF16"],
    size: "2.3 GB",
  },
  // TTS 1.7B Base models
  "Qwen3-TTS-12Hz-1.7B-Base": {
    shortName: "1.7B Base",
    fullName: "Qwen3-TTS 12Hz 1.7B Base",
    description: "Higher quality voice cloning capabilities",
    category: "tts",
    capabilities: ["Voice Cloning"],
    size: "4.2 GB",
  },
  "Qwen3-TTS-12Hz-1.7B-Base-4bit": {
    shortName: "1.7B Base 4-bit",
    fullName: "Qwen3-TTS 12Hz 1.7B Base (MLX 4-bit)",
    description: "Quantized base model for lower-memory voice cloning",
    category: "tts",
    capabilities: ["Voice Cloning", "4-bit"],
    size: "2.2 GB",
  },
  // TTS 1.7B CustomVoice
  "Qwen3-TTS-12Hz-1.7B-CustomVoice": {
    shortName: "1.7B CustomVoice",
    fullName: "Qwen3-TTS 12Hz 1.7B CustomVoice",
    description: "Premium quality with 9 built-in voices",
    category: "tts",
    capabilities: ["Text to Speech"],
    size: "4.2 GB",
  },
  "Qwen3-TTS-12Hz-1.7B-CustomVoice-4bit": {
    shortName: "1.7B Custom 4-bit",
    fullName: "Qwen3-TTS 12Hz 1.7B CustomVoice (MLX 4-bit)",
    description: "Quantized CustomVoice model with lower VRAM requirements",
    category: "tts",
    capabilities: ["Text to Speech", "4-bit"],
    size: "2.2 GB",
  },
  // TTS 1.7B VoiceDesign models
  "Qwen3-TTS-12Hz-1.7B-VoiceDesign": {
    shortName: "1.7B VoiceDesign",
    fullName: "Qwen3-TTS 12Hz 1.7B VoiceDesign",
    description: "Generate voices from text descriptions",
    category: "tts",
    capabilities: ["Voice Design"],
    size: "4.2 GB",
  },
  "Qwen3-TTS-12Hz-1.7B-VoiceDesign-4bit": {
    shortName: "1.7B Design 4-bit",
    fullName: "Qwen3-TTS 12Hz 1.7B VoiceDesign (MLX 4-bit)",
    description: "Quantized VoiceDesign for creative voices on 16GB devices",
    category: "tts",
    capabilities: ["Voice Design", "4-bit"],
    size: "2.2 GB",
  },
  "Qwen3-TTS-12Hz-1.7B-VoiceDesign-8bit": {
    shortName: "1.7B Design 8-bit",
    fullName: "Qwen3-TTS 12Hz 1.7B VoiceDesign (MLX 8-bit)",
    description: "8-bit VoiceDesign balancing VRAM usage and quality",
    category: "tts",
    capabilities: ["Voice Design", "8-bit"],
    size: "2.9 GB",
  },
  "Qwen3-TTS-12Hz-1.7B-VoiceDesign-bf16": {
    shortName: "1.7B Design BF16",
    fullName: "Qwen3-TTS 12Hz 1.7B VoiceDesign (MLX bf16)",
    description: "BF16 VoiceDesign with best timbre quality",
    category: "tts",
    capabilities: ["Voice Design", "BF16"],
    size: "4.2 GB",
  },
  "Kokoro-82M": {
    shortName: "Kokoro 82M",
    fullName: "Kokoro-82M by hexgrad",
    description:
      "Lightweight multilingual TTS model with 54 built-in voices (Rust runtime integration pending)",
    category: "tts",
    capabilities: ["Text to Speech", "54 Voices", "24 kHz"],
    size: "346 MB",
  },
  // Text Chat
  "Qwen3-0.6B-GGUF": {
    shortName: "Qwen3 Chat 0.6B GGUF",
    fullName: "Qwen3 0.6B (GGUF Q8_0)",
    description: "Compact text-to-text model in GGUF format",
    category: "chat",
    capabilities: ["Text Chat", "GGUF", "Q8_0"],
    size: "1.0 GB",
  },
  "Qwen3-1.7B-GGUF": {
    shortName: "Qwen3 Chat 1.7B GGUF",
    fullName: "Qwen3 1.7B (GGUF Q8_0)",
    description: "Higher-quality 1.7B chat model in GGUF format",
    category: "chat",
    capabilities: ["Text Chat", "GGUF", "Q8_0"],
    size: "2.2 GB",
  },
  "Qwen3-4B-GGUF": {
    shortName: "Qwen3 Chat 4B GGUF",
    fullName: "Qwen3 4B (GGUF Q4_K_M)",
    description: "4B chat model in GGUF format (Q4_K_M only)",
    category: "chat",
    capabilities: ["Text Chat", "GGUF", "Q4_K_M"],
    size: "2.5 GB",
  },
  "Qwen3-8B-GGUF": {
    shortName: "Qwen3 Chat 8B GGUF",
    fullName: "Qwen3 8B (GGUF Q4_K_M)",
    description: "8B chat model in GGUF format (Q4_K_M only)",
    category: "chat",
    capabilities: ["Text Chat", "GGUF", "Q4_K_M"],
    size: "5.2 GB",
  },
  "Qwen3.5-0.8B": {
    shortName: "Qwen3.5 0.8B",
    fullName: "Qwen3.5 0.8B (GGUF Q4_K_M)",
    description: "Compact hybrid multimodal Qwen3.5 checkpoint",
    category: "chat",
    capabilities: ["Chat", "Multimodal", "GGUF", "Q4_K_M"],
    size: "0.74 GB",
  },
  "Qwen3.5-2B": {
    shortName: "Qwen3.5 2B",
    fullName: "Qwen3.5 2B (GGUF Q4_K_M)",
    description: "Balanced hybrid multimodal Qwen3.5 checkpoint",
    category: "chat",
    capabilities: ["Chat", "Multimodal", "GGUF", "Q4_K_M"],
    size: "1.95 GB",
  },
  "Qwen3.5-4B": {
    shortName: "Qwen3.5 4B",
    fullName: "Qwen3.5 4B (GGUF Q4_K_M)",
    description: "Higher-quality hybrid multimodal Qwen3.5 checkpoint",
    category: "chat",
    capabilities: ["Chat", "Multimodal", "GGUF", "Q4_K_M"],
    size: "3.41 GB",
  },
  "Qwen3.5-9B": {
    shortName: "Qwen3.5 9B",
    fullName: "Qwen3.5 9B (GGUF Q4_K_M)",
    description: "Largest requested hybrid multimodal Qwen3.5 checkpoint",
    category: "chat",
    capabilities: ["Chat", "Multimodal", "GGUF", "Q4_K_M"],
    size: "6.60 GB",
  },
  "LFM2.5-1.2B-Instruct-GGUF": {
    shortName: "LFM2.5 1.2B Instruct",
    fullName: "LFM2.5 1.2B Instruct (GGUF Q4_K_M)",
    description: "On-device instruction chat model from Liquid AI",
    category: "chat",
    capabilities: ["Text Chat", "GGUF", "Q4_K_M"],
    size: "0.68 GB",
  },
  "LFM2.5-1.2B-Thinking-GGUF": {
    shortName: "LFM2.5 1.2B Thinking",
    fullName: "LFM2.5 1.2B Thinking (GGUF Q4_K_M)",
    description: "Reasoning-tuned on-device chat model from Liquid AI",
    category: "chat",
    capabilities: ["Text Chat", "GGUF", "Q4_K_M", "Thinking"],
    size: "0.68 GB",
  },
  "Gemma-3-1b-it": {
    shortName: "Gemma 3 1B",
    fullName: "Gemma 3 1B Instruct",
    description: "Lightweight Gemma 3 instruction model for local chat",
    category: "chat",
    capabilities: ["Text Chat", "Instruction Tuned"],
    size: "2.1 GB",
  },
  "Gemma-3-4b-it": {
    shortName: "Gemma 3 4B",
    fullName: "Gemma 3 4B Instruct",
    description: "Higher-quality Gemma 3 instruction model for local chat",
    category: "chat",
    capabilities: ["Text Chat", "Instruction Tuned"],
    size: "8.0 GB",
  },
  "Whisper-Large-v3-Turbo": {
    shortName: "Whisper v3 Turbo",
    fullName: "Whisper Large v3 Turbo",
    description:
      "OpenAI Whisper Turbo model for fast multilingual local transcription",
    category: "asr",
    capabilities: [
      "Transcription",
      "Multilingual",
      "Offline",
      "Streaming deltas",
    ],
    size: "1.5 GB",
  },
  // ASR 0.6B models
  "Qwen3-ASR-0.6B": {
    shortName: "ASR 0.6B",
    fullName: "Qwen3-ASR 0.6B",
    description: "Fast speech-to-text, 52 languages",
    category: "asr",
    capabilities: ["Transcription"],
    size: "1.8 GB",
  },
  "Qwen3-ASR-0.6B-4bit": {
    shortName: "ASR 0.6B 4-bit",
    fullName: "Qwen3-ASR 0.6B (MLX 4-bit)",
    description: "Lightweight ASR for real-time transcription on smaller GPUs",
    category: "asr",
    capabilities: ["Transcription", "4-bit"],
    size: "0.7 GB",
  },
  "Qwen3-ASR-0.6B-8bit": {
    shortName: "ASR 0.6B 8-bit",
    fullName: "Qwen3-ASR 0.6B (MLX 8-bit)",
    description: "8-bit ASR with higher accuracy and modest footprint",
    category: "asr",
    capabilities: ["Transcription", "8-bit"],
    size: "0.9 GB",
  },
  "Qwen3-ASR-0.6B-bf16": {
    shortName: "ASR 0.6B BF16",
    fullName: "Qwen3-ASR 0.6B (MLX bf16)",
    description: "BF16 precision ASR for top accuracy",
    category: "asr",
    capabilities: ["Transcription", "BF16"],
    size: "1.5 GB",
  },
  // ASR 1.7B models
  "Qwen3-ASR-1.7B": {
    shortName: "ASR 1.7B",
    fullName: "Qwen3-ASR 1.7B",
    description: "High-quality speech-to-text, 52 languages",
    category: "asr",
    capabilities: ["Transcription"],
    size: "4.4 GB",
  },
  "Qwen3-ASR-1.7B-4bit": {
    shortName: "ASR 1.7B 4-bit",
    fullName: "Qwen3-ASR 1.7B (MLX 4-bit)",
    description: "Quantized 1.7B ASR for RTX 4090 / M3 workloads",
    category: "asr",
    capabilities: ["Transcription", "4-bit"],
    size: "1.5 GB",
  },
  "Qwen3-ASR-1.7B-8bit": {
    shortName: "ASR 1.7B 8-bit",
    fullName: "Qwen3-ASR 1.7B (MLX 8-bit)",
    description: "8-bit ASR for high fidelity transcripts on Apple Silicon",
    category: "asr",
    capabilities: ["Transcription", "8-bit"],
    size: "2.3 GB",
  },
  "Qwen3-ASR-1.7B-bf16": {
    shortName: "ASR 1.7B BF16",
    fullName: "Qwen3-ASR 1.7B (MLX bf16)",
    description: "BF16 ASR providing maximum quality and accuracy",
    category: "asr",
    capabilities: ["Transcription", "BF16"],
    size: "3.8 GB",
  },
  "Qwen3-ForcedAligner-0.6B": {
    shortName: "ForcedAligner 0.6B",
    fullName: "Qwen3-ForcedAligner 0.6B",
    description: "Aligns transcript text to precise speech timestamps",
    category: "asr",
    capabilities: ["Forced Alignment", "Word timestamps"],
    size: "1.7 GB",
  },
  "Qwen3-ForcedAligner-0.6B-4bit": {
    shortName: "ForcedAligner 0.6B 4-bit",
    fullName: "Qwen3-ForcedAligner 0.6B (MLX 4-bit)",
    description: "Quantized forced aligner for low-memory alignment workflows",
    category: "asr",
    capabilities: ["Forced Alignment", "Word timestamps", "4-bit"],
    size: "0.7 GB",
  },
  "Parakeet-TDT-0.6B-v2": {
    shortName: "Parakeet v2",
    fullName: "Parakeet-TDT 0.6B v2",
    description: "English FastConformer-TDT ASR model in .nemo format",
    category: "asr",
    capabilities: ["Transcription", "Word timestamps"],
    size: "4.6 GB",
  },
  "Parakeet-TDT-0.6B-v3": {
    shortName: "Parakeet v3",
    fullName: "Parakeet-TDT 0.6B v3",
    description: "Multilingual FastConformer-TDT ASR model in .nemo format",
    category: "asr",
    capabilities: ["Transcription", "25 EU languages"],
    size: "9.3 GB",
  },
  "diar_streaming_sortformer_4spk-v2.1": {
    shortName: "Sortformer 4spk",
    fullName: "Streaming Sortformer 4spk v2.1",
    description:
      "Streaming speaker diarization model from NVIDIA in .nemo format",
    category: "asr",
    capabilities: ["Diarization", "Up to 4 speakers", "Streaming"],
    size: "0.5 GB",
  },
  // Voxtral
  "Voxtral-Mini-4B-Realtime-2602": {
    shortName: "Voxtral 4B",
    fullName: "Voxtral Mini 4B Realtime",
    description: "Realtime streaming ASR from Mistral AI",
    category: "asr",
    capabilities: ["Transcription", "Realtime"],
    size: "8.0 GB",
  },
};
